[package]
name = "tensorous"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tensorous"
path = "src/lib.rs"

[dependencies]
dot = { git = "https://github.com/przygienda/dot-rust.git" }
num = "0.4"
rand = "0.8"
tensorous-derive = { path = "tensorous-derive" }
blas = "0.22"
seq-macro = "0.3"

[dev-dependencies]
proptest = "1.0.0"
